# Generated by Django 3.1.2 on 2024-07-14 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
